server:
  port: 8080

spring:
  data:
    cassandra:
      keyspace-name: urlspace
      contact-points: 127.0.0.1
      port: 9042
      username: admin
      password: password
      local-datacenter: datacenter1

  cloud:
    zookeeper:
      connect-string: localhost:2181
